version: 0.0
os: linux
files:
  - source: /run_pt.sh
    destination: /home/ec2-user/tryapp/
  - source: /jmeter5
    destination: /home/ec2-user/tryapp/jmeter5
  - source: /jmeter_testplans
    destination: /home/ec2-user/tryapp/jmeter_testplans
hooks:
  BeforeInstall:
    #- location: Scripts/UnzipResourceBundle.sh
    #- location: Scripts/UnzipDataBundle.sh
  AfterInstall:
    #- location: /home/ec2-user/tryapp/run_pt.sh
    #  timeout: 180
  ApplicationStart:
    - location: run_pt.sh
      #timeout: 180
  ValidateService:
    - location: save_test_logs.sh
      #timeout: 180
      #runas: codedeployuser